name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches:
    - dev
    paths:
    - '**.js'
    - '**.properties'

env:
  PM2_APP_ID: 2

jobs:
  deploy-dev-on-raspberry:
    runs-on: self-hosted

    steps:
      - name: Pull repository
        run: |
          export REPO=~/$GITHUB_REPOSITORY/dev
          echo $REPO
          cd $REPO
          git pull --recurse-submodules

      - name: Restart pm2 process
        run: |
          pm2 stop $PM2_APP_ID
          pm2 flush $PM2_APP_ID
          pm2 start $PM2_APP_ID
          sleep 30
          pm2 logs $PM2_APP_ID --lines 100 --nostream
